log_level: debug
log_timestamp: true
max_age: 2h

notifications:
- name: github-releases
  feeds:
  - name: cf-releases
    url: https://github.com/cloudfoundry/cf-deployment/releases.atom
  - name: bosh-releases
    url: https://github.com/cloudfoundry/bosh/releases.atom
  - name: capi-releases
    url: https://github.com/cloudfoundry/capi-release/releases.atom
  - name: cf-for-k8s
    url: https://github.com/cloudfoundry/cf-for-k8s/releases.atom
  - name: concourse
    url: https://github.com/concourse/concourse/releases.atom
  - name: stratos-portal
    url: https://github.com/cloudfoundry/stratos/releases.atom
  - name: mongodb-operator
    url: https://github.com/mongodb/mongodb-enterprise-kubernetes/releases.atom
  - name: prometheus-operator
    url: https://github.com/prometheus-operator/prometheus-operator/releases.atom
  - name: grafana-operator
    url: https://github.com/integr8ly/grafana-operator/releases.atom
  - name: postgres-operator
    url: https://github.com/CrunchyData/postgres-operator/releases.atom
  - name: tekton-operator
    url: https://github.com/tektoncd/operator/releases.atom
  - name: ytt
    url: https://github.com/vmware-tanzu/carvel-ytt/releases.atom
  - name: kapp
    url: https://github.com/vmware-tanzu/carvel-kapp/releases.atom
  - name: kbld
    url: https://github.com/vmware-tanzu/carvel-kbld/releases.atom
  - name: vendir
    url: https://github.com/vmware-tanzu/carvel-vendir/releases.atom
  - name: kapp-controller
    url: https://github.com/vmware-tanzu/carvel-kapp-controller/releases.atom
  - name: terraform
    url: https://github.com/hashicorp/terraform/releases.atom
  - name: carvel-terraform-provider
    url: https://github.com/vmware-tanzu/terraform-provider-carvel/releases.atom
  - name: hetznercloud-terraform-provider
    url: https://github.com/hetznercloud/terraform-provider-hcloud/releases.atom
  - name: tekton-pipeline
    url: https://github.com/tektoncd/pipeline/releases.atom
  - name: ingress-nginx
    url: https://github.com/kubernetes/ingress-nginx/releases.atom
  - name: cert-manager
    url: https://github.com/jetstack/cert-manager/releases.atom
  - name: cilium
    url: https://github.com/cilium/cilium/releases.atom
  - name: hetznercloud-cli
    url: https://github.com/hetznercloud/cli/releases.atom
  - name: hetznercloud-csi-driver
    url: https://github.com/hetznercloud/csi-driver/releases.atom
  - name: hetznercloud-controller-manager
    url: https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases.atom
  - name: knative-serving
    url: https://github.com/knative/serving/releases.atom
  - name: knative-cli
    url: https://github.com/knative/client/releases.atom
  - name: knative-eventing
    url: https://github.com/knative/eventing/releases.atom
  - name: knative-operator
    url: https://github.com/knative/operator/releases.atom
  - name: kpack
    url: https://github.com/pivotal/kpack/releases.atom
  - name: kpack-cli
    url: https://github.com/vmware-tanzu/kpack-cli/releases.atom
  - name: dex
    url: https://github.com/dexidp/dex/releases.atom
  - name: authelia
    url: https://github.com/authelia/authelia/releases.atom
  - name: istio
    url: https://github.com/istio/istio/releases.atom
  - name: longhorn
    url: https://github.com/longhorn/longhorn/releases.atom
  - name: prometheus
    url: https://github.com/prometheus/prometheus/releases.atom
  - name: grafana
    url: https://github.com/grafana/grafana/releases.atom
  - name: loki
    url: https://github.com/grafana/loki/releases.atom
  - name: cf-cli
    url: https://github.com/cloudfoundry/cli/releases.atom
  - name: bosh-cli
    url: https://github.com/cloudfoundry/bosh-cli/releases.atom
  webhooks:
  - url: http://localhost:9876/test
    template: |
      {
        "@type": "MessageCard",
        "@context": "https://schema.org/extensions",
        "summary": "{{ .Title }}",
        "themeColor": "1188dd",
        "title": "{{ .Title }}",
        "sections": [
          {
            "activityTitle": "{{ .Feed.Title }}",
            "activitySubtitle": "{{ .Item.Title }}",
            "activityImage": "{{ .Feed.Image }}",
            "facts": [
              {
                "name": "Updated:",
                "value": "{{ .Item.Updated }}"
              }
            ],
            "text": "{{ .MarkdownContent | replace "\"" "'" | replace "\\" "" | replace "\n" "          \n" }}"
          }
        ],
        "potentialAction": [
          {
            "@type": "OpenUri",
            "name": "GitHub - Release Notes",
            "targets": [
              {
                "os": "default",
                "uri": "{{ .Item.Link }}"
              }
            ]
          }
        ]
      }
