log_level: debug
log_timestamp: true
max_age: 2h

notifications:
- name: github-releases
  feeds:
  - name: cf-releases
    url: https://github.com/cloudfoundry/cf-deployment/releases.atom
  - name: bosh-releases
    url: https://github.com/cloudfoundry/bosh/releases.atom
  - name: capi-releases
    url: https://github.com/cloudfoundry/capi-release/releases.atom
  - name: diego-releases
    url: https://github.com/cloudfoundry/diego-release/releases.atom
  - name: bosh-stemcells
    url: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases.atom
  - name: cf-cli
    url: https://github.com/cloudfoundry/cli/releases.atom
  - name: bosh-cli
    url: https://github.com/cloudfoundry/bosh-cli/releases.atom
  - name: concourse
    url: https://github.com/concourse/concourse/releases.atom
  - name: mongodb-operator
    url: https://github.com/mongodb/mongodb-enterprise-kubernetes/releases.atom
  - name: prometheus-operator
    url: https://github.com/prometheus-operator/prometheus-operator/releases.atom
  - name: cnpg-io
    url: https://github.com/cloudnative-pg/cloudnative-pg/releases.atom
  - name: ytt
    url: https://github.com/vmware-tanzu/carvel-ytt/releases.atom
  - name: kapp
    url: https://github.com/vmware-tanzu/carvel-kapp/releases.atom
  - name: kbld
    url: https://github.com/vmware-tanzu/carvel-kbld/releases.atom
  - name: vendir
    url: https://github.com/vmware-tanzu/carvel-vendir/releases.atom
  - name: kapp-controller
    url: https://github.com/vmware-tanzu/carvel-kapp-controller/releases.atom
  # - name: terraform
  #   url: https://github.com/hashicorp/terraform/releases.atom
  - name: opentofu
    url: https://github.com/opentofu/opentofu/releases.atom
  - name: carvel-terraform-provider
    url: https://github.com/vmware-tanzu/terraform-provider-carvel/releases.atom
  - name: hetznercloud-terraform-provider
    url: https://github.com/hetznercloud/terraform-provider-hcloud/releases.atom
  - name: vcloud-terraform-provider
    url: https://github.com/vmware/terraform-provider-vcd/releases.atom
  - name: nsxt-terraform-provider
    url: https://github.com/vmware/terraform-provider-nsxt/releases.atom
  - name: ingress-nginx
    url: https://github.com/kubernetes/ingress-nginx/releases.atom
  - name: cert-manager
    url: https://github.com/jetstack/cert-manager/releases.atom
  - name: cilium
    url: https://github.com/cilium/cilium/releases.atom
  - name: hetznercloud-cli
    url: https://github.com/hetznercloud/cli/releases.atom
  - name: hetznercloud-csi-driver
    url: https://github.com/hetznercloud/csi-driver/releases.atom
  - name: hetznercloud-controller-manager
    url: https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases.atom
  - name: knative-serving
    url: https://github.com/knative/serving/releases.atom
  - name: knative-cli
    url: https://github.com/knative/client/releases.atom
  - name: knative-eventing
    url: https://github.com/knative/eventing/releases.atom
  - name: knative-operator
    url: https://github.com/knative/operator/releases.atom
  - name: kpack
    url: https://github.com/pivotal/kpack/releases.atom
  - name: kpack-cli
    url: https://github.com/vmware-tanzu/kpack-cli/releases.atom
  - name: dex
    url: https://github.com/dexidp/dex/releases.atom
  # - name: authelia
  #   url: https://github.com/authelia/authelia/releases.atom
  - name: csi-driver-nfs
    url: https://github.com/kubernetes-csi/csi-driver-nfs/releases.atom
  - name: csi-driver-smb
    url: https://github.com/kubernetes-csi/csi-driver-smb/releases.atom
  - name: longhorn
    url: https://github.com/longhorn/longhorn/releases.atom
  - name: prometheus
    url: https://github.com/prometheus/prometheus/releases.atom
  - name: grafana
    url: https://github.com/grafana/grafana/releases.atom
  - name: loki
    url: https://github.com/grafana/loki/releases.atom
  - name: kubermatic-kkp
    url: https://github.com/kubermatic/kubermatic/releases.atom
  - name: kubermatic-kkp-dashboard
    url: https://github.com/kubermatic/dashboard/releases.atom
  - name: kubermatic-kubeone
    url: https://github.com/kubermatic/kubeone/releases.atom
  - name: kubermatic-operating-system-manager
    url: https://github.com/kubermatic/operating-system-manager/releases.atom
  - name: kubermatic-machine-controller
    url: https://github.com/kubermatic/machine-controller/releases.atom
  webhooks:
  - url: http://localhost:9876/test
    template: |
      {
         "type":"message",
         "attachments":[
            {
               "contentType":"application/vnd.microsoft.card.adaptive",
               "contentUrl":null,
               "content":{
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.6",
                  "body": [
                      {
                          "type": "TextBlock",
                          "text": "{{ .Title }}",
                          "size": "Large",
                          "style": "heading",
                          "wrap": true
                      },
                      {
                          "type": "TextBlock",
                          "text": "{{ .Feed.Title }}",
                          "size": "Medium",
                          "style": "heading",
                          "wrap": true
                      },
                      {
                          "type": "TextBlock",
                          "text": "{{ .Item.Title }}",
                          "size": "Default",
                          "separator": true,
                          "wrap": true
                      },
                      {
                          "type": "TextBlock",
                          "text": "**Updated:** {{ .Item.Updated }}",
                          "size": "Default",
                          "separator": true,
                          "wrap": true
                      },
                      {
                          "type": "TextBlock",
                          "text": "{{ .MarkdownContent | replace "\"" "'" | replace "\\" "" | replace "\n" "          \n" }}",
                          "size": "Default",
                          "wrap": true
                      },
                      {
                          "type": "ActionSet",
                          "actions": [
                              {
                                  "type": "Action.OpenUrl",
                                  "title": "GitHub - Release Notes",
                                  "url": "{{ .Item.Link }}",
                                  "iconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/240px-Octicons-mark-github.svg.png"
                              }
                          ]
                      }
                  ]
               }
            }
         ]
      }
